name: Feature request
description: Suggest an improvement
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem are you trying to solve?
      description: Describe your situation rather than a solution.
    validations:
      required: true
  - type: textarea
    id: idea
    attributes:
      label: What would you like to see?
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: What have you tried or considered?
    validations:
      required: false
