# Generated by Django 6.1.1 on 2026-10-08 08:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sandbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The account's username, kept for the logs.", max_length=40, unique=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(db_index=True, help_text='The sandbox and everything in it are deleted then.')),
                ('client_ip', models.CharField(blank=True, help_text="The visitor's address, for the rate limit; deleted with the sandbox.", max_length=45)),
                ('user', models.OneToOneField(blank=True, help_text='Empty once the visitor left and the account was deleted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sandbox', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'demo sandbox',
                'verbose_name_plural': 'demo sandboxes',
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
