# Generated by Django 6.1.1 on 2026-10-04 07:33

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import tracker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_title', models.CharField(max_length=200, verbose_name='role')),
                ('posting_url', models.URLField(blank=True, max_length=1000, verbose_name='job posting URL')),
                ('location', models.CharField(blank=True, max_length=200)),
                ('work_mode', models.CharField(blank=True, choices=[('onsite', 'On-site'), ('hybrid', 'Hybrid'), ('remote', 'Remote')], max_length=10)),
                ('status', models.CharField(choices=[('wishlist', 'Wishlist'), ('applied', 'Applied'), ('interviewing', 'Interviewing'), ('offer', 'Offer'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('no_response', 'No response')], default='applied', max_length=20)),
                ('date_applied', models.DateField(blank=True, null=True)),
                ('salary', models.CharField(blank=True, help_text="Free text, e.g. '650-700k DKK + pension'.", max_length=200)),
                ('contact_name', models.CharField(blank=True, max_length=200, verbose_name='contact person')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='contact email')),
                ('source', models.CharField(blank=True, help_text='Where you found it, e.g. LinkedIn or a referral.', max_length=100)),
                ('next_follow_up', models.DateField(blank=True, null=True, verbose_name='next follow-up')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': [models.OrderBy(models.F('date_applied'), descending=True, nulls_last=True), '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('cv', 'CV'), ('cover_letter', 'Cover letter')], max_length=20)),
                ('label', models.CharField(help_text="A name you will recognise later, e.g. 'CV - backend focus, Oct 2026'.", max_length=200)),
                ('file', models.FileField(upload_to=tracker.models.document_upload_to)),
                ('original_filename', models.CharField(max_length=255)),
                ('size', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('created', 'Created'), ('status', 'Status changed'), ('edited', 'Edited'), ('note', 'Note')], max_length=10)),
                ('from_status', models.CharField(blank=True, choices=[('wishlist', 'Wishlist'), ('applied', 'Applied'), ('interviewing', 'Interviewing'), ('offer', 'Offer'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('no_response', 'No response')], max_length=20)),
                ('to_status', models.CharField(blank=True, choices=[('wishlist', 'Wishlist'), ('applied', 'Applied'), ('interviewing', 'Interviewing'), ('offer', 'Offer'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('no_response', 'No response')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tracker.application')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('website', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'ordering': [django.db.models.functions.text.Lower('name')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_company_name_ci', violation_error_message='A company with this name already exists.')],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='tracker.company'),
        ),
        migrations.AddField(
            model_name='application',
            name='cover_letter',
            field=models.ForeignKey(blank=True, limit_choices_to={'kind': 'cover_letter'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cover_letter_applications', to='tracker.document', verbose_name='cover letter sent'),
        ),
        migrations.AddField(
            model_name='application',
            name='cv',
            field=models.ForeignKey(blank=True, limit_choices_to={'kind': 'cv'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cv_applications', to='tracker.document', verbose_name='CV sent'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status'], name='tracker_app_status_58d1d3_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['next_follow_up'], name='tracker_app_next_fo_b08430_idx'),
        ),
    ]
