# Generated by Django 6.1.1 on 2026-10-05 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='posting_text',
            field=models.TextField(blank=True, help_text='The ad text, kept so you can still read it after the posting is taken down.', verbose_name='copy of the job ad'),
        ),
        migrations.AddField(
            model_name='application',
            name='posting_text_saved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicationevent',
            name='kind',
            field=models.CharField(choices=[('created', 'Created'), ('status', 'Status changed'), ('edited', 'Edited'), ('note', 'Note'), ('follow_up', 'Follow-up')], max_length=10),
        ),
    ]
